name: data-06-weatherpy
channels:
  - conda-forge
dependencies:
  - python     =3.7
  - gmaps      =0.9.*
  - jupyterlab =3.3.*
  - nodejs     =17.9.*
  - pandas     =1.3.*
  - numpy      =1.21.*
  - requests   =2.28.*
  - scipy      =1.7.*
